app/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
import forms
from flask.ext.login import login_user, logout_user, login_required, current_user
from support import flash_errors, pretty_date, pretty_time, dict2obj
import models
from datetime import datetime, date, timedelta

#------------------------------------------------------------------------------#
# Controllers
#------------------------------------------------------------------------------#

bp = Blueprint('incentas', __name__, template_folder='templates',
              static_folder='static')
user_management = Blueprint('user_management', __name__,
                            template_folder='templates', static_folder='static')
challenges = Blueprint('challenges', __name__,
                            template_folder='templates', static_folder='static')
measurements = Blueprint('measurements', __name__,
                            template_folder='templates', static_folder='static')

blueprints = [bp, user_management, challenges, measurements]

@measurements.context_processor
def utility_processor():
    return dict(pretty_date=pretty_date, pretty_time=pretty_time)

@bp.route("/")
def index():
    if current_user.is_authenticated():
        return render_template("overview.html")
    return render_template("index.html")

@user_management.route("/login", methods=['GET','POST'])
def login():
    form = forms.LoginForm()
    if form.validate_on_submit():
        class LoginException(Exception): pass
        try:
            user = models.User.query.filter(models.User.username ==
                                        form.name.data).scalar()
            if user is None:
                raise LoginException("Username unknown.")
            if not user.check_password(form.passwd.data):
                raise LoginException("Wrong password.")
            login_user(user)
            flash("Hello, %s." % current_user.fullname, "info")
            return redirect(request.args.get("next") or url_for("incentas.index"))
        except LoginException as err:
            flash(" ".join(err.args), "danger")
    flash_errors(form)
    return render_template("login.html", form=form)

@user_management.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("incentas.index"))


@user_management.route("/settings", methods=['GET','POST'])
@login_required
def settings():
    user = current_user
    obj = dict2obj(fullname=user.fullname, height=user.height)
    form = forms.SettingsForm(obj=obj)
    if form.validate_on_submit():
        if form.password.data:
            user.set_password(form.password.data)
            flash('Password updated', 'success')
        user.fullname = form.fullname.data
        user.height = form.height.data
        models.db.session.commit()
        return redirect(url_for('.settings'))
    flash_errors(form)
    return render_template('settings.html', form=form)


@user_management.route("/register", methods=['GET','POST'])
def register():
    form = forms.RegisterForm()
    if form.validate_on_submit():
        user = models.User(form.username.data, form.password.data,
                           form.fullname.data)
        flash("Account created.  Now, please log in", "success")
        return redirect(url_for('.login'))
    flash_errors(form)
    return render_template("register.html", form=form)

@challenges.route("/challenge")
@login_required
def index():
    return render_template("list_challenges.html",
                           challenges=current_user.challenges)

@challenges.route("/challenge/active")
@challenges.route("/challenge/active/<slack>")
@login_required
def list_active_challenges(slack=2):
    slack = float(slack)
    latest_endtime = datetime.now() - timedelta(slack)
    flash(latest_endtime)
    active_challenges = [ch for ch in current_user.challenges if ch.end >= latest_endtime]
    return render_template("list_challenges.html", challenges=active_challenges)

@challenges.route("/challenge/<int:id>", methods=['GET','POST'])
@login_required
def challenge(id):
    ch = models.Challenge.query.filter_by(id=id).scalar()
    if ch is None:
        flash("Unknown challenge", "warning")
        return redirect(url_for('.list_challenges'))
    if current_user != ch.user:
        flash("Access denied", "error")
        return redirect(url_for('.list_challenges'))

    form = forms.challenge_forms[ch.type]()
    form.init_from_challenge(ch)
    if form.validate_on_submit():
        try:
            ch.update_from_form_data(form.data)
            return redirect(url_for('.challenge', id=id))
        except forms.FormValidationError as err:
            models.db.session.rollback()
            flash(err.message, 'error')
    if request.method == 'GET':
        form.load_from_challenge(ch, today=date.today())
    flash_errors(form)
    return render_template("%s_challenge.html"%ch.type, challenge=ch, form=form)

@measurements.route('/measurement', methods=['GET','POST'])
@login_required
def index():
    obj = dict2obj(new_measurements=[dict2obj(type=m.label) for m in current_user.measurements])
    form = forms.AddMeasurementsForm(obj=obj)
    if form.validate_on_submit():
        timestamp = datetime.now()
        for measurement in form.new_measurements:
            value = measurement.data['value']
            if value is None: continue
            series_label = measurement.data['type']
            series = current_user.measurements.filter_by(label=series_label).one()
            models.Measurement(series, value, timestamp)
        return redirect(url_for('.index'))
    flash_errors(form)
    return render_template('measurements.html', form=form, user=current_user)

from flask_crud import *

fields=('value', 'timestamp')

@measurements.record_once
def register_crud_bps(state):
    for bp in (
        crud_bp(models.db.session,
                lambda label: current_user.measurements.filter_by(label=label).one().series,
                fields, '/measurement/manage/<label>'),
        crud_bp(models.db.session,
                lambda : current_user.measurements, ('label',),
                '/measurement/manage', models.MeasurementCategory, lambda d:
                dict({'user_id':current_user.id}, **d)),
    ):
        state.app.register_blueprint(bp)

# Error Handlers

@bp.app_errorhandler(500)
def internal_error(error):
    models.db_session.rollback()
    return render_template('500.html'), 500

@bp.route('/<path:invalid_path>')
def internal_error(invalid_path):
    return render_template('404.html'), 404

app/templates/challenge.html
{% extends "template.html" %}
{% block title %} - Challenge {{challenge.title}}{% endblock %}

{% block content_no_row %}
<div class="row">
	<h1>{{challenge.title}}</h1>
	<div class="col-sm-10 col-sm-offset-1">
		<div class="row">
			{% with context=challenge.bootstrap_context() %}
			<div class="jumbotron jumbotron-challenge-{{context}}">
				<div class="row">
					<div class="challenge-value col-sm-4">
					{% block challenge_jumbotron_left scoped %}
					{% endblock %}
					</div>
					<div class="challenge-points center-block col-sm-2 col-sm-offset-1">
						<div class="value">{{"%8.1f" % challenge.calc_points()}}</div>
						<div>points{{"" if challenge.is_overdue() else " so far"}}</div>
					</div>
					<div class="challenge-time col-sm-4 col-sm-offset-1 text-right">
						<div>
							<span class="done"> {{challenge.days_left()}} </span>
							/
							<span class="target"> {{challenge.duration()}} </span>
							<span class="unit"> days left</span>
						</div>
						<div>
							{{ progress_bar(100*challenge.time_ratio(), context)}}
						</div>
					</div>
				</div>
				<div class="row">
				</div>
				<div><b class="highlight">Your task:</b> {{ challenge.description }}</div>
				<div class="smallprint">
					<span class="highlight">{{challenge.points_success}}</span> points to win;
					<span class="highlight">{{challenge.points_fail}}</span> points to lose.
					Runs from <span class="highlight">{{challenge.start}}</span>
					to <span class="highlight">{{challenge.end}}</span>.
				</div>
			{% endwith %}
		</div>
	</div>

	<form method="POST" action="">
		{% block form %}
		{% endblock %}
		</form>
		<div>
</div>
{% endblock %}

{% macro datepicker(date_field, class_="col-sm-3", pre="") -%}
<div class="{{class_}}">
	<div class="pull-right">
		{% if pre %}
		<div>
			{{pre|safe}}
		</div>
		{% endif %}
		<div>
			{{ date_field(class="datepicker-hidden-input", type="hidden") }}
			<span class="datepicker-display">{{date_field.data}}</span>
			<button type="button" class="btn btn-default btn-sm datepicker-button glyphicon glyphicon-th"></button>
		</div>
	</div>
</div>
{%- endmacro %}

{% macro progress_bar(percentage, level) %}
		<div class="progress">
			<div class="progress-bar progress-bar-{{level}}" style="width: {{percentage}}%">
			</div>
		</div>
{% endmacro %}

app/templates/crud_edit.html
{% extends "template.html" %}
{% block title %} - CRUD Edit{% endblock %}
{% block content_no_row %}
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<h1>Edit</h1>
		<form method="post">
			{{ form.hidden_tag() }}
			{% for field in form %}
				{{labeled_inputfield_group(field)}}
			{% endfor %}
			<div class="row">
				<div class="col-sm-2">
					<button type="submit" class="btn btn-primary">Submit</button>
				</div>
			</div>
		</form>
	</div>
</div>
{% endblock %}


{% macro labeled_inputfield_group(element) %}
{% if element.type == "CSRFTokenField" %}
{% elif element.type in "TextField DecimalField DateTimeField QuerySelectField".split() %}
<div class="form-group">
	{{ element.label }}{{inputfield(element)}}
</div>
{% else %}
<div class="error">unknown field type "{{element.type}}"</div>
{% endif %}
{% endmacro %}

{% macro inputfield(element) %}
	{{ element(class_="form-control", placeholder=element.label.text) }}
{% endmacro %}

app/templates/crud_index.html
{% extends "template.html" %}
{% block title %} - CRUD{% endblock %}
{% block content_no_row %}
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<h1>Crud</h1>
		{% if allow_create %}
		<a href="{{url_for('.create')}}">create new row</a>
		{% endif %}
		<table class="table table-striped">
			<thead>
				<tr>
					{% for field in fields %}
					<th>{{field}}</th>
					{% endfor %}
					<th>actions</th>
				</tr>
			</thead>
			<tbody>
				{% for element in query.all() %}
				<tr>
					{% for field in fields %}
					<td>
						{{element[field]}}
					</td>
					{% endfor %}
					<td>
						<a href="{{url_for('.edit', id=element.id, **kwargs)}}">edit</a>
						<a class="delete-trigger" delete-id="{{element.id}}">delete</a>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
{% endblock %}

{% block bottom_extra %}
<script language="javascript"> 
	$('.delete-trigger').click(function(ev){
		id = $(ev.target).attr('delete-id')
		console.log(id)
		$.post("{{url_for('.delete', id="-1", **kwargs)}}".replace("-1",id), {}, function () {
			window.location.href = "{{url_for('.index', **kwargs)}}"
		})
	})

</script>
{% endblock %}

app/templates/daily_evaluation_challenge.html
{% extends "challenge.html" %}
{% block challenge_jumbotron_left %}
<div>
	<span class="done"> todo </span>
	/
	<span class="target"> todo </span>
	<span class="unit"> todo </span>
</div>
<div>
	{{ progress_bar(42, context)}}
</div>
{% endblock %}

{% block form %}
<h2>A form</h2>
{{form.hidden_tag()}}
{% for ev in form.evaluations %}
<div class="row">
	{{ev.hidden_tag()}}
	<div class="col-sm-3">
		<div class="pull-right">
			{{ev.timestamp.data}}
		</div>
	</div>
	<div class="btn-group col-sm-5" data-toggle="buttons">
		{% for choice in ev.evaluation %}
		<label class="btn btn-{{choice.data}} {{"active" if choice.checked else ""}}">
			<input name="{{choice.name}}" value="{{choice.data}}" type="radio" {{"checked" if choice.checked else ""}}>
			{{choice.label}}
		</label>
		{% endfor %}
	</div>
</div>
{% endfor %}
<div class="row">
	<div class="form-group col-sm-2 col-sm-offset-1">
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>
</div>

{% endblock %}

app/templates/index.html
{% extends "template.html" %}
{% block title %} - Home{% endblock %}
{% block content %}
<h1>Welcome!</h1>
Please log in or register.
{% endblock %}

app/templates/list_challenges.html
{% extends "template.html" %}
{% block title %} - Challenges for {{current_user.fullname}}{% endblock %}
{% block content_no_row %}
<div class="row">
	<h1>{{current_user.fullname}}'s challenges</h1>
	total points = {{current_user.calc_challenge_points()}}
	<ol>
		{% for challenge in challenges %}
		<li>
		<a href="{{url_for('.challenge',id=challenge.id)}}">{{challenge.title}}</a>
			{{challenge.start}} - {{challenge.end}}
			{{challenge.calc_points()}} points,
			{{challenge.summary or "summary to be implemented"}}
		</li>
		{% endfor %}
	</ol>
</div>
{% endblock %}

app/templates/login.html
{% extends "template.html" %}
{% block title %} - Login{% endblock %}
{% block content_no_row %}
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<h1>Login</h1>
		<h3>Please log in.</h3>
		<form method="POST" action="">
			{{form.hidden_tag()}}
			{% for element in (form.name, form.passwd) %}
			<div class="form-group">
				{{ element.label }}{{ element(class_="form-control", placeholder=element.label.text) }}
			</div>
			{% endfor %}
			<button type="submit" class="btn btn-primary">Login</button>
			<span class="help-block">Need an account? <a href="/register">Signup!!</a></span>
		</form>
	</div>
</div>
{% endblock %}

app/templates/measurements.html
{% extends "template.html" %}
{% block title %} - Measurements{% endblock %}

{% block content_no_row %}
<div class="row">
	<h1>Measurements</h1>
	<div class="col-sm-10 col-sm-offset-1">
		<form method="POST" action="">
			{% block form %}
			{{form.hidden_tag()}}
			<h2>Add new measurements</h2>
			<div class="row form-group">
				{% for measurement in form.new_measurements %}
				{{measurement.hidden_tag()}}
				<div class="col-sm-2">
					{{measurement.value(class_="form-control", placeholder=measurement.form.type.data)}}
				</div>
				{% endfor %}
				<div class="col-sm-2">
					<button type="submit" class="btn btn-primary">Submit</button>
				</div>
			</div>
			<a href="{{url_for('crud/measurement/manage.index')}}">manage measurement categories</a>
		</form>

			<h2> Previous Measurements </h2>
			{% for measurement_category in user.measurements %}
			<h3>{{measurement_category.label}}</h3>
			<a href="{{url_for('crud/measurement/manage/<label>.index', label=measurement_category.label)}}">edit records</a>
			<dl class="dl-horizontal">
				{% for m in measurement_category.series %}
				<dt>
				{%call tooltip(pretty_time(m.timestamp), placement='left')%}
					{{pretty_date(m.timestamp)}}
				{%endcall%}
				</dt>
				<dd>{{"%.4g"%m.value}}</dd>
				{% endfor %}
			</dl>
				
			{% endfor %}
			{% endblock %}
	</div>
</div>
{% endblock %}

{% macro tooltip(title) %}
<span class="tooltip-trigger" data-toggle="tooltip" data-title="{{title}}" {%for k,v in kwargs.items()%} data-{{k}}="{{v}}" {%endfor%}>
	{{ caller() }}
</span>
{% endmacro %}

app/templates/overview.html
{% extends "template.html" %}
{% block title %} - Home{% endblock %}
{% block content %}
<h1>Overview</h1>

<div class="task jumbotron col-sm-offset-1 col-sm-10">
    <h2><small>Current task:</small> 40km</h2>
    Track 40 km doing sports.
    <div class="row">
	<div class="col-md-8">
	    started: <span class="timestamp">2014-04-20</span>
	    <br>
	    deadline: <span class="timestamp">2014-04-20</span>
	</div>
	<div class="col-md-4">
	    <button type="button" class="btn btn-primary">Complete</button>
	</div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
	{% for week in range(5,7) %}
	<div class="focus panel panel-success">
	    <div class="panel-heading">
		<h3 class="panel-title">Week {{week}} <small>2014-04-14 &mdash; 2014-04-20</small></h3>
	    </div>
	    <div class="panel-body">
		{% set focus = {'drink': {'mon': 'success', 'tue': 'warning', 'wed': 'danger'}, 'relax': {'mon': 'warning', 'tue': 'warning', 'wed': 'success'}} %}
		{% for item in focus %}
		<div class="row">
		    <div class="col-sm-3 text-right">{{item}}</div>
		    <div class="col-sm-9 btn-group">
			{% for day in "mon tue wed thu fri sat sun".split() %}
			<div class="btn-group">
			    <button type="button" class="btn btn-sm btn-{{focus[item].get(day,'default')}} dropdown-toggle" data-toggle="dropdown">
				{{day[0]}}
			    </button>
			    <ul class="dropdown-menu" role="menu">
				<li><a href="#">success</a></li>
				<li><a href="#">alert</a></li>
				<li><a href="#">danger</a></li>
			    </ul>
			</div>
			{% endfor %}
		    </div>
		</div>
		{% endfor %}
		<div class="row">
		    <div class="col-sm-12">

			<div class="btn-group">
			    {% for trackable in "sports drink meals relax sleep planning".split() %}
			    <div class="btn-group">
				<button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
				    {{trackable}}
				</button>
				<ul class="dropdown-menu" role="menu">
				    <li><a href="#">success</a></li>
				    <li><a href="#">alert</a></li>
				    <li><a href="#">danger</a></li>
				</ul>
			    </div>
			    {% endfor %}
			</div>
		    </div>
		</div>
	    </div>
	</div>
	{% endfor %}
    </div>

    <div class="col-sm-6">
	<div class="focus panel panel-info">
	    <div class="panel-heading">
		<h3 class="panel-title">Measurements</h3>
	    </div>
	    <div class="panel-body">
		<form>
		</form>
	    </div>
	</div>
	<div class="focus panel panel-warning">
	    <div class="panel-heading">
		<h3 class="panel-title">Progress</h3>
	    </div>
	    <div class="panel-body">
		<div class="progress">
		    <div class="progress-bar progress-bar-success" style="width: 70%"> week 1 </div>
		    <div class="progress-bar progress-bar-warning" style="width: 20%"> </div>
		    <div class="progress-bar progress-bar-danger" style="width: 10%"> </div>
		</div>
		<div class="progress">
		    <div class="progress-bar progress-bar-success" style="width: 30%"> </div>
		    <div class="progress-bar progress-bar-warning" style="width: 50%"> week 2 </div>
		    <div class="progress-bar progress-bar-danger" style="width: 20%"> </div>
		</div>
		<div class="progress">
		    <div class="progress-bar progress-bar-success" style="width: 70%"> week 3 </div>
		    <div class="progress-bar progress-bar-warning" style="width: 10%"> </div>
		    <div class="progress-bar progress-bar-danger" style="width: 20%"> </div>
		</div>

	    </div>
	</div>
    </div>
</div>

{% endblock %}

app/templates/register.html
{% extends "template.html" %}
{% block title %} - Register{% endblock %}
{% block content_no_row %}
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<h1>Welcome!</h1>
		<h2>Please register.</h2>
		<form method="POST" action="">
			{{form.hidden_tag()}}
			{% for element in (form.username, form.password, form.fullname) %}
			<div class="form-group">
				{{ element.label }}{{ element(class_="form-control", placeholder=element.label.text) }}
			</div>
			{% endfor %}
			<button type="submit" class="btn btn-primary">Register</button>
		</form>
		<span class="help-block">Already registered? <a href="/login">Login!</a></span>
	</div>
</div>
{% endblock %}

app/templates/settings.html
{% extends "template.html" %}
{% block title %} - Settings{% endblock %}
{% block content_no_row %}
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<h1>{{current_user}}'s Settings</h1>
		<form method="POST" action="">
			{{form.hidden_tag()}}
			{{ labeled_inputfield_group(form.fullname) }}
			{{ labeled_inputfield_group(form.height) }}
			<div class="form-group">
				{{ form.password.label }}
				<div class="row">
					<div class="col-sm-6"> {{ inputfield(form.password) }} </div>
					<div class="col-sm-6"> {{ inputfield(form.confirm) }} </div>
				</div>
			</div>
			<button type="submit" class="btn btn-primary">Save</button>
		</form>
	</div>
</div>
{% endblock %}

{% macro labeled_inputfield_group(element) %}
{% if element.type in "TextField DecimalField".split() %}
<div class="form-group">
	{{ element.label }}{{inputfield(element)}}
</div>
{% else %}
<div class="error">unknown field type "{{element.type}}"</div>
{% endif %}
{% endmacro %}

{% macro inputfield(element) %}
	{{ element(class_="form-control", placeholder=element.label.text) }}
{% endmacro %}

app/templates/target_value_challenge.html
{% extends "challenge.html" %}
{% block challenge_jumbotron_left %}
<div>
	<span class="done"> {{challenge.current_value()}} </span>
	/
	<span class="target"> {{challenge.target_value}} </span>
	<span class="unit"> {{challenge.unit}} done</span>
</div>
<div>
	{{ progress_bar(100*challenge.value_ratio(), context)}}
</div>
{% endblock %}

{% block form %}
<h2>Add new progress</h2>
{{form.hidden_tag()}}
<div class="row">
	{{form.add_progress.hidden_tag()}}
	{% with pre=form.add_progress.timestamp.label %}
	{{datepicker(form.add_progress.timestamp, pre=pre)}}
	{% endwith %}
	<div class="col-sm-2">
		{{ form.add_progress.value.label }}
		<div class="input-group">
			{{ form.add_progress.value(class_="form-control", placeholder=form.add_progress.value.label.text) }}
			<span class="input-group-addon">{{challenge.unit}}</span>
		</div>
	</div>
	<div class="col-sm-6">
		{{ form.add_progress.note.label }}
		{{ form.add_progress.note(class_="form-control", placeholder=form.add_progress.note.label.text) }}
	</div>
</div>
<h2>Modify previous progress</h2>
{% for progress in form.existing_progress %}
<div class="row">
	{{progress.hidden_tag()}}
	{{datepicker(progress.timestamp)}}
	<div class="col-sm-2">
		{{ progress.value.label(class_="sr-only") }}
		<div class="input-group">
			{{ progress.value(class_="form-control", placeholder=progress.value.label.text) }}
			<span class="input-group-addon">{{challenge.unit}}</span>
		</div>
	</div>
	<div class="col-sm-6">
		{{ progress.note.label(class_="sr-only") }}
		{{ progress.note(class_="form-control", placeholder=progress.note.label.text) }}
	</div>
</div>
{% endfor %}
<div class="row">
	<div class="form-group col-sm-2 col-sm-offset-1">
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>
</div>
{% endblock %}

app/templates/template.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Incentas{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.css')}}">
        <link rel="stylesheet" href="{{url_for('static',filename='css/datepicker3.css')}}">
        <script type=text/javascript>
          $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
        </script>
    </head>
    <body>
        <!-- Static navbar -->
        <div class="navbar navbar-default">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{url_for('incentas.index')}}">Incentas</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    {% if current_user.is_authenticated() %}
                    <li><a href="{{url_for('challenges.index')}}">Challenges</a></li>
                    <li><a href="{{url_for('measurements.index')}}">Measurements</a></li>
                    {% else %}
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated() %}
                    <li><a href="{{url_for('user_management.settings')}}">Settings</a></li>
                    <li><a href="{{url_for('user_management.logout')}}">Logout</a></li>
                    {% else %}
                    <li><a href="{{url_for('user_management.register')}}">Register</a></li>
                    <li><a href="{{url_for('user_management.login')}}">Login</a></li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>


        <div class="container">

            <div id="main" role="main">
                <div class="alert-messages">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                    {% for category, message in messages %}
                    <div class="alert alert-dismissable alert-{{category}} fade in">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        {{ message }}
                    </div>
                    {% endfor %}
                    {% endif %}
                    {% endwith %}
                </div>
                {% block content_no_row %}
                <div class="row">
                    <div class="col-sm-10 col-sm-offset-1">
                        {% block content %}{% endblock %}
                    </div>
                </div>
                {% endblock %}
            </div>
        </div>

        <footer>
        {% block footer %}{% endblock %}
        </footer>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<'+'script src="{{url_for('static',filename='js/libs/jquery.min.js')}}"><\/script>')
        </script>
        <script defer src="{{url_for('static',filename='js/libs/modernizr-2.0.6.min.js')}}"></script>
        <script defer src="{{url_for('static',filename='js/libs/bootstrap.min.js')}}"></script>
        <script defer src="{{url_for('static',filename='js/libs/bootstrap-datepicker.js')}}"></script>
        <script defer src="{{url_for('static',filename='js/plugins.js')}}"></script>
        <script defer src="{{url_for('static',filename='js/script.js')}}"></script>
        {% block bottom_extra %}{% endblock %}
    </body>

</html>